name: "📦 .deb › Build"
run-name: "📦 .deb › Build"

on:
  workflow_dispatch:
    inputs:

      # ---------------------------------------------------------------------------------------
      #   ENABLE:   Will show all types of commits, including uncategorized
      #   DISABLE:  WIll only show actions that have been categorized using the format
      #                type(scope): description
      #                type: description
      # ---------------------------------------------------------------------------------------

      EDIT_CHANGELOG:
        description:  "🗂️ Dont Edit Changelog"
        required:     true
        default:      true
        type:         boolean

jobs:

    # ---------------------------------------------------------------------------------------
    #   JOB > INITIALIZE
    # ---------------------------------------------------------------------------------------

    job-build:
        name: >-
          📦 Build › Initialize
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
        steps:

            - name: "✅ Start"
              id: task_build_start
              run: |
                echo "Starting build"

            # ---------------------------------------------------------------------------------------
            #   Job > Initialize > Checkout
            # ---------------------------------------------------------------------------------------

            - name: "☑️ Checkout"
              id: task_build_checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: 'Get Previous tag'
              id: previoustag
              uses: "WyriHaximus/github-action-get-previous-tag@v1"
              with:
                fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
                #workingDirectory: another/path/where/a/git/repo/is/checked/out # Optional alternative working directory

            - name: "🔨 Get Current Version"
              id: task_build_getver
              run: |
                echo -e ${{ steps.previoustag.outputs.tag }}

            # ---------------------------------------------------------------------------------------
            #   Get version from package.json VERSION value
            # ---------------------------------------------------------------------------------------

            - name: "🔨 Build .deb"
              id: task_build_run
              run: |
                sudo apt install tree
                command="update.sh"
                input_EDIT_CHANGELOG=${{ inputs.EDIT_CHANGELOG }}

                if [ "${input_EDIT_CHANGELOG}" = true ]; then
                  command+=" --skipChangelog"
                fi

                if [[ ! -z "${{ steps.previoustag.outputs.tag }}" ]]; then
                  command+=" --current ${{ steps.previoustag.outputs.tag }}"
                else
                  echo -e "No version specified, skipping build"
                  exit 1
                fi

                # make file runnable, might not be necessary
                chmod +x "${GITHUB_WORKSPACE}/update.sh"

                echo -e "Sending command: ${command}"
                eval "./$command"

                tree

            - name: "📦 Commit"
              id: task_build_commit
              uses: stefanzweifel/git-auto-commit-action@v5

