name: "📦 Build from Source"
run-name: "📦 Build from Source"

on:
  workflow_dispatch:
    inputs:

      # ---------------------------------------------------------------------------------------
      #   ENABLE:   Will show all types of commits, including uncategorized
      #   DISABLE:  WIll only show actions that have been categorized using the format
      #                type(scope): description
      #                type: description
      # ---------------------------------------------------------------------------------------

      EDIT_CHANGELOG:
        description:  "🗂️ Dont Edit Changelog"
        required:     true
        default:      true
        type:         boolean

jobs:

    # ---------------------------------------------------------------------------------------
    #   JOB > INITIALIZE
    # ---------------------------------------------------------------------------------------

    job-initialize:
        name: >-
          📦 Publish › Initialize
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
        steps:

            - name: "✅ Start"
              id: task_initialize_start
              run: |
                echo "Starting build"

            # ---------------------------------------------------------------------------------------
            #   Job > Initialize > Checkout
            # ---------------------------------------------------------------------------------------

            - name: "☑️ Checkout"
              id: task_initialize_checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            # ---------------------------------------------------------------------------------------
            #   Get version from package.json VERSION value
            # ---------------------------------------------------------------------------------------

            - name: "👁️‍🗨️ Run Script"
              id: task_initialize_bash_run
              run: |
                sudo apt install tree
                command="update.sh"
                input_EDIT_CHANGELOG=${{ inputs.EDIT_CHANGELOG }}
                if [ "${input_EDIT_CHANGELOG}" = true ]; then
                  command+=" -s"
                fi

                # make file runnable, might not be necessary
                chmod +x "${GITHUB_WORKSPACE}/update.sh"
                eval "./$command"

                tree

            - name: "👁️‍🗨️ Commit"
              uses: stefanzweifel/git-auto-commit-action@v5
